# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名称')),
                ('password', models.CharField(max_length=255, verbose_name='用户密码')),
                ('age', models.IntegerField(default=18, verbose_name='用户年龄')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户昵称')),
                ('birthday', models.DateTimeField(default=datetime.datetime(2018, 10, 8, 16, 36, 21, 655791), verbose_name='用户生日')),
                ('email', models.EmailField(max_length=255, verbose_name='用户邮箱')),
                ('gender', models.BooleanField(default=0)),
            ],
        ),
    ]
