# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header',
            field=models.ImageField(default='/static/img/banel/default.png', max_length=255, upload_to='', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 9, 21, 18, 22, 633313), verbose_name='用户生日'),
        ),
    ]
